"""old fix

Revision ID: b0843ba8d01b
Revises: 46cd135255c2
Create Date: 2025-12-18 03:15:20.656919

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0843ba8d01b'
down_revision = '46cd135255c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shares')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shares',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shared_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shared_with_email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('folder_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('shares_file_id_fkey')),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name=op.f('shares_folder_id_fkey')),
    sa.ForeignKeyConstraint(['shared_by_id'], ['users.id'], name=op.f('shares_shared_by_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('shares_pkey'))
    )
    # ### end Alembic commands ###
